# Generated by Django 5.2.13 on 2026-04-11 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_time', models.DateTimeField(db_index=True, help_text='When the attendance was recorded')),
                ('scan_date', models.DateField(db_index=True, help_text='Date extracted from scan_time')),
                ('verification_method', models.CharField(choices=[('rfid', 'RFID Card'), ('bar_code', 'Bar Code'), ('qr', 'QR Code'), ('manual', 'Manual Entry'), ('ble', 'BLE Tag'), ('nfc', 'NFC')], default='manual', max_length=20)),
                ('verification_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('fraud_suspected', 'Fraud Suspected'), ('duplicate', 'Duplicate Entry')], db_index=True, default='success', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='For biometric methods', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw data from scanner/reader')),
                ('remarks', models.TextField(blank=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.class')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='firmware.edgenode')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'verbose_name': 'Class Attendance',
                'verbose_name_plural': 'Class Attendances',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_date', models.DateField(db_index=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('morning_sessions', models.PositiveIntegerField(default=0)),
                ('afternoon_sessions', models.PositiveIntegerField(default=0)),
                ('evening_sessions', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.class')),
            ],
            options={
                'verbose_name': 'Daily Attendance Summary',
                'verbose_name_plural': 'Daily Attendance Summaries',
                'ordering': ['-summary_date'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('attempt', 'Attempt'), ('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry'), ('blocked', 'Blocked')], db_index=True, max_length=20)),
                ('method', models.CharField(choices=[('rfid', 'RFID Card'), ('bar_code', 'Bar Code'), ('qr', 'QR Code'), ('manual', 'Manual Entry'), ('ble', 'BLE Tag'), ('nfc', 'NFC')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='verification/captures/')),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('attempt_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to process in milliseconds', null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='classroom.classattendance')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='firmware.edgenode')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='core.student')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['scan_date'], name='classroom_c_scan_da_3d2057_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['verification_status'], name='classroom_c_verific_51a7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['student', 'scan_date'], name='classroom_c_student_d0cdba_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['class_obj', 'scan_date'], name='classroom_c_class_o_0da4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['node', 'scan_time'], name='classroom_c_node_id_c94caf_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['student', 'class_obj', 'scan_date'], name='classroom_c_student_9ac691_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['class_obj', 'verification_status'], name='classroom_c_class_o_c33da6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['summary_date', 'class_obj'], name='classroom_d_summary_4408e3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['attendance_percentage'], name='classroom_d_attenda_a73381_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancesummary',
            unique_together={('class_obj', 'summary_date')},
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['attempt_time'], name='classroom_v_attempt_da291b_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['event_type', 'success'], name='classroom_v_event_t_2e009e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['node', 'attempt_time'], name='classroom_v_node_id_8b4326_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['student', 'attempt_time'], name='classroom_v_student_0a2130_idx'),
        ),
    ]
