# Generated by Django 5.2.13 on 2026-04-13 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('student_reg_number', models.CharField(blank=True, db_index=True, help_text='Student registration number from scan', max_length=20)),
                ('class_code', models.CharField(blank=True, db_index=True, help_text='Class code from scan', max_length=30)),
                ('scan_method', models.CharField(choices=[('qr', 'QR Code'), ('barcode', 'Barcode'), ('ocr', 'OCR Text'), ('manual', 'Manual Entry'), ('rfid', 'RFID/NFC'), ('face', 'Face Recognition')], default='qr', max_length=20)),
                ('scan_device', models.CharField(blank=True, help_text='Node UUID or camera ID', max_length=100)),
                ('scan_location', models.CharField(blank=True, help_text='Physical location of scan', max_length=200)),
                ('raw_qr_data', models.TextField(blank=True, help_text='Raw QR code data if applicable')),
                ('raw_ocr_text', models.TextField(blank=True, help_text='Raw OCR extracted text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('validation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='classroom.classattendance')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='core.class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='core.student')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='classroom_a_session_2e6939_idx'), models.Index(fields=['status', 'expires_at'], name='classroom_a_status_8cebe8_idx'), models.Index(fields=['student_reg_number'], name='classroom_a_student_84eefa_idx'), models.Index(fields=['class_code'], name='classroom_a_class_c_73a69a_idx'), models.Index(fields=['created_at'], name='classroom_a_created_b240d3_idx'), models.Index(fields=['scan_device'], name='classroom_a_scan_de_34cb4a_idx')],
            },
        ),
    ]
