# Generated by Django 5.2.13 on 2026-04-11 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLETag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('tag_uuid', models.CharField(db_index=True, help_text='Unique tag identifier', max_length=36, unique=True)),
                ('hardware_id', models.CharField(help_text='MAC address or hardware serial', max_length=50, unique=True)),
                ('tag_type', models.CharField(choices=[('wearable', 'Wearable Wristband'), ('card', 'ID Card'), ('sticker', 'Adhesive Sticker'), ('phone', 'Smartphone App')], default='wearable', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('charging', 'Charging'), ('retired', 'Retired'), ('maintenance', 'Under Maintenance')], db_index=True, default='available', max_length=20)),
                ('battery_level', models.PositiveSmallIntegerField(default=100, help_text='Battery percentage')),
                ('last_charged', models.DateTimeField(blank=True, null=True)),
                ('battery_threshold', models.PositiveSmallIntegerField(default=20, help_text='Alert when battery below this level')),
                ('last_ping_time', models.DateTimeField(blank=True, null=True)),
                ('last_rssi', models.IntegerField(blank=True, null=True)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('total_hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('last_known_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='access.accesszone')),
            ],
            options={
                'ordering': ['tag_uuid'],
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('lost', 'Tag Lost'), ('damaged', 'Tag Damaged')], default='active', max_length=20)),
                ('assignment_notes', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_assignments', to='core.staff')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_tags', to='core.staff')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vms.bletag')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='bletag',
            name='current_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vms.tagassignment'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('purpose', models.CharField(choices=[('meeting', 'Official Meeting'), ('lecture', 'Guest Lecture'), ('research', 'Research Collaboration'), ('conference', 'Conference/Workshop'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('purpose_description', models.TextField(blank=True)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('alien_id', 'Alien ID'), ('company_id', 'Company ID')], default='national_id', max_length=20)),
                ('id_number', models.CharField(db_index=True, help_text='ID number provided', max_length=50)),
                ('id_verified', models.BooleanField(default=False)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='visitors/id_photos/')),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, help_text='Organization/company the visitor represents', max_length=150)),
                ('organization_phone', models.CharField(blank=True, max_length=20)),
                ('organization_email', models.EmailField(blank=True, max_length=254)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('average_visit_duration', models.DurationField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('host_department', models.ForeignKey(help_text='Department being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_visitors', to='core.department')),
                ('host_person', models.ForeignKey(help_text='Staff member being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_hosted_visitors', to='core.person')),
                ('id_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_visitors', to='core.staff')),
                ('institution', models.ForeignKey(help_text='Institution being visited', on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='core.institution')),
                ('person', models.OneToOneField(help_text='Base person information', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_profile', to='core.person')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-last_visit', 'person__last_name'],
            },
        ),
        migrations.AddField(
            model_name='tagassignment',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_assignments', to='vms.visitor'),
        ),
        migrations.AddField(
            model_name='bletag',
            name='current_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tags', to='vms.visitor'),
        ),
        migrations.CreateModel(
            name='BlacklistedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('reason_category', models.CharField(choices=[('security', 'Security Threat'), ('misconduct', 'Misconduct'), ('trespassing', 'Trespassing'), ('theft', 'Theft'), ('violence', 'Violent Behavior'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_description', models.TextField()),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('removed', 'Removed')], default='active', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('evidence_notes', models.TextField(blank=True)),
                ('evidence_images', models.JSONField(default=list, help_text='List of image URLs')),
                ('blacklisted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms_blacklisted_visitors', to='core.staff')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_blacklist', to='core.staff')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='vms.visitor')),
            ],
            options={
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('check_in_time', models.DateTimeField(db_index=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('escorted', 'Escorted'), ('blacklisted', 'Blacklisted'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('check_in_notes', models.TextField(blank=True)),
                ('check_out_notes', models.TextField(blank=True)),
                ('total_movements', models.PositiveIntegerField(default=0)),
                ('zones_visited', models.JSONField(default=list, help_text='List of zone IDs visited')),
                ('assigned_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='vms.bletag')),
                ('check_in_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='firmware.edgenode')),
                ('check_out_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='firmware.edgenode')),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visitors', to='core.staff')),
                ('checked_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_visitors', to='core.staff')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='vms.visitor')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitorMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('enter', 'Enter Zone'), ('exit', 'Exit Zone'), ('ping', 'Heartbeat Ping'), ('dwell', 'Dwell Alert'), ('alert', 'Movement Alert'), ('path', 'Path Movement')], db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('rssi', models.IntegerField(blank=True, help_text='Received signal strength indicator', null=True)),
                ('distance_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance in meters', max_digits=6, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Location accuracy in meters', max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('dwell_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_movements', to='firmware.edgenode')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='vms.bletag')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='vms.visitor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_movements', to='access.accesszone')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='vms.visitorvisit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('alert_type', models.CharField(choices=[('zone_breach', 'Unauthorized Zone Entry'), ('dwell_time', 'Excessive Dwell Time'), ('tag_lost', 'Tag Signal Lost'), ('low_battery', 'Low Battery'), ('movement_anomaly', 'Suspicious Movement'), ('time_exceeded', 'Visit Time Exceeded')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional alert data')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='core.staff')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='core.staff')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vms.bletag')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vms.visitor')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_alerts', to='access.accesszone')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vms.visitorvisit')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='current_visit',
            field=models.ForeignKey(blank=True, help_text='Current active visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vms.visitorvisit'),
        ),
        migrations.CreateModel(
            name='MovementPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('path_type', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('vehicle', 'Vehicle'), ('unknown', 'Unknown')], default='walking', max_length=20)),
                ('zones_visited', models.JSONField(default=list, help_text='Ordered list of zone IDs visited')),
                ('coordinates', models.JSONField(default=list, help_text='List of [lat, lng] coordinates')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance in meters', max_digits=10, null=True)),
                ('total_duration', models.DurationField()),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=6, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='vms.visitor')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='vms.visitorvisit')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TagActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('activity_type', models.CharField(choices=[('power_on', 'Power On'), ('power_off', 'Power Off'), ('battery_update', 'Battery Update'), ('movement', 'Movement Detected'), ('alert', 'Alert Triggered'), ('config_change', 'Configuration Change')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField(default=dict, help_text='Additional activity data')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_activities', to='firmware.edgenode')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='vms.bletag')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tag', 'timestamp'], name='vms_tagacti_tag_id_f643ba_idx'), models.Index(fields=['activity_type', 'timestamp'], name='vms_tagacti_activit_d0ae94_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['assigned_at', 'released_at'], name='vms_tagassi_assigne_637b87_idx'),
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['status'], name='vms_tagassi_status_e829ce_idx'),
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['tag', 'status'], name='vms_tagassi_tag_id_51e589_idx'),
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['visitor', 'status'], name='vms_tagassi_visitor_42e324_idx'),
        ),
        migrations.AddIndex(
            model_name='bletag',
            index=models.Index(fields=['tag_uuid'], name='vms_bletag_tag_uui_1f7706_idx'),
        ),
        migrations.AddIndex(
            model_name='bletag',
            index=models.Index(fields=['hardware_id'], name='vms_bletag_hardwar_6e2971_idx'),
        ),
        migrations.AddIndex(
            model_name='bletag',
            index=models.Index(fields=['status'], name='vms_bletag_status_1bc1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='bletag',
            index=models.Index(fields=['battery_level'], name='vms_bletag_battery_5e5ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='bletag',
            index=models.Index(fields=['last_ping_time'], name='vms_bletag_last_pi_af2351_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedvisitor',
            index=models.Index(fields=['visitor', 'status'], name='vms_blackli_visitor_63b6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedvisitor',
            index=models.Index(fields=['expires_at'], name='vms_blackli_expires_ba0364_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedvisitor',
            index=models.Index(fields=['blacklisted_by'], name='vms_blackli_blackli_50fea6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorvisit',
            index=models.Index(fields=['check_in_time', 'check_out_time'], name='vms_visitor_check_i_e3c8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorvisit',
            index=models.Index(fields=['status'], name='vms_visitor_status_43f4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorvisit',
            index=models.Index(fields=['visitor', 'status'], name='vms_visitor_visitor_969487_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['visitor', 'timestamp'], name='vms_visitor_visitor_19bab5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['tag', 'timestamp'], name='vms_visitor_tag_id_b8cf62_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['zone', 'timestamp'], name='vms_visitor_zone_id_c85535_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['event_type', 'timestamp'], name='vms_visitor_event_t_b9ac01_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['timestamp'], name='vms_visitor_timesta_307461_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['visit', 'zone', 'timestamp'], name='vms_visitor_visit_i_02200c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormovement',
            index=models.Index(fields=['visitor', 'event_type', 'timestamp'], name='vms_visitor_visitor_dcdc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoralert',
            index=models.Index(fields=['visitor', 'triggered_at'], name='vms_visitor_visitor_e734f6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoralert',
            index=models.Index(fields=['alert_type', 'severity'], name='vms_visitor_alert_t_7ab121_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoralert',
            index=models.Index(fields=['status', 'triggered_at'], name='vms_visitor_status_089381_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['id_number'], name='vms_visitor_id_numb_5dc684_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization'], name='vms_visitor_organiz_900889_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['host_person'], name='vms_visitor_host_pe_14ca01_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['host_department'], name='vms_visitor_host_de_4a6cef_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['purpose'], name='vms_visitor_purpose_8e1e95_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_visit'], name='vms_visitor_last_vi_89d650_idx'),
        ),
        migrations.AddIndex(
            model_name='movementpath',
            index=models.Index(fields=['visitor', 'start_time'], name='vms_movemen_visitor_33b317_idx'),
        ),
        migrations.AddIndex(
            model_name='movementpath',
            index=models.Index(fields=['visit', 'start_time'], name='vms_movemen_visit_i_9d159f_idx'),
        ),
        migrations.AddIndex(
            model_name='movementpath',
            index=models.Index(fields=['path_type'], name='vms_movemen_path_ty_039e24_idx'),
        ),
    ]
