# Generated by Django 5.2.13 on 2026-04-13 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('session_type', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out'), ('tag_assign', 'Tag Assignment'), ('tag_release', 'Tag Release'), ('ocr_process', 'OCR Processing')], db_index=True, max_length=20)),
                ('extracted_data', models.JSONField(default=dict, help_text='Data extracted from ID/QR scan')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('company_id', 'Company ID'), ('unknown', 'Unknown')], default='unknown', help_text='Type of ID that was scanned', max_length=20)),
                ('raw_ocr_text', models.TextField(blank=True, help_text='Raw OCR extracted text')),
                ('raw_qr_data', models.TextField(blank=True, help_text='Raw QR code data')),
                ('captured_image', models.ImageField(blank=True, help_text='Image captured during scan', null=True, upload_to='visitor_sessions/')),
                ('scan_method', models.CharField(choices=[('qr', 'QR Code'), ('barcode', 'Barcode'), ('ocr', 'OCR Text'), ('manual', 'Manual Entry'), ('rfid', 'RFID/NFC'), ('face', 'Face Recognition')], default='ocr', max_length=20)),
                ('scan_device', models.CharField(blank=True, max_length=100)),
                ('scan_location', models.CharField(blank=True, max_length=200)),
                ('provided_info', models.JSONField(blank=True, default=dict, help_text='Information provided by visitor during check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_info', 'Awaiting Additional Info'), ('awaiting_tag', 'Awaiting Tag Assignment'), ('processing', 'Processing'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('validation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('assigned_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vms.bletag')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vms.visitorvisit')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vms.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='vms_visitor_session_fe5032_idx'), models.Index(fields=['status', 'expires_at'], name='vms_visitor_status_eb170e_idx'), models.Index(fields=['visitor'], name='vms_visitor_visitor_2cc115_idx'), models.Index(fields=['session_type'], name='vms_visitor_session_fd1421_idx'), models.Index(fields=['created_at'], name='vms_visitor_created_06a33c_idx')],
            },
        ),
    ]
