# Generated by Django 5.2.13 on 2026-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_add_visitor_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
