# Generated by Django 5.2.13 on 2026-04-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vms', '0003_alter_visitor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.staff'),
        ),
    ]
