# Generated by Django 5.2.13 on 2026-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareversion',
            name='firmware_file',
            field=models.FileField(upload_to='microcode/'),
        ),
    ]
