# Generated by Django 5.2.13 on 2026-04-11 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_url', models.CharField(blank=True, max_length=500)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('recipient_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.person')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['recipient_email', 'queued_at'], name='notificatio_recipie_8759be_idx'), models.Index(fields=['status'], name='notificatio_status_18a272_idx'), models.Index(fields=['message_id'], name='notificatio_message_096fbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance'), ('visitor', 'Visitor'), ('access', 'Access'), ('system', 'System'), ('security', 'Security')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('related_object_id', models.CharField(blank=True, max_length=50)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'), models.Index(fields=['priority', 'status'], name='notificatio_priorit_27f109_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_number', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, help_text='What triggered this SMS', max_length=50)),
                ('recipient_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.person')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['recipient_number', 'queued_at'], name='notificatio_recipie_af2e8b_idx'), models.Index(fields=['status'], name='notificatio_status_532cc1_idx'), models.Index(fields=['message_id'], name='notificatio_message_8ae491_idx')],
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('session_type', models.CharField(choices=[('2fa', 'Two-Factor Authentication'), ('checkin', 'Visitor Check-in'), ('checkout', 'Visitor Check-out'), ('alert', 'Alert Response')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_menu', models.CharField(default='main', max_length=50)),
                ('user_input', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('interaction_log', models.JSONField(default=list, help_text='Log of USSD interactions')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='core.person')),
                ('two_factor_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_session', to='access.twofactorsession')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id'], name='notificatio_session_c13c22_idx'), models.Index(fields=['phone_number', 'status'], name='notificatio_phone_n_c4850e_idx'), models.Index(fields=['last_activity'], name='notificatio_last_ac_c09663_idx')],
            },
        ),
    ]
