# Generated by Django 5.2.13 on 2026-04-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessattempt',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_attempts', to='firmware.edgenode'),
        ),
        migrations.AddField(
            model_name='accessattempt',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_attempts', to='core.person'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='firmware.edgenode'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.person'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='college',
            field=models.ForeignKey(blank=True, help_text='Restrict to specific college', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.college'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Restrict to specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Restrict to specific program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Restrict to specific school', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='specific_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='core.person'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_zones', to='core.college'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_zones', to='core.department'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_zones', to='core.institution'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='parent_zone',
            field=models.ForeignKey(blank=True, help_text='Parent zone (e.g., Building for Floor)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_zones', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='accesszone',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_zones', to='core.school'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='accessattempt',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_attempts', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='geofenceboundary',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='core.person'),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='twofactorsession',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_sessions', to='core.person'),
        ),
        migrations.AddField(
            model_name='twofactorsession',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_sessions', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='twofactorlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='access.twofactorsession'),
        ),
        migrations.AddField(
            model_name='zoneaccessrule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='zonehierarchy',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='access.accesszone'),
        ),
        migrations.AddField(
            model_name='zonehierarchy',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='access.accesszone'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['code'], name='access_acce_code_fcf52b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['zone_type'], name='access_acce_zone_ty_f26512_idx'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['access_level'], name='access_acce_access__7501d2_idx'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['parent_zone'], name='access_acce_parent__8956ab_idx'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['institution', 'zone_type'], name='access_acce_institu_791d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesszone',
            index=models.Index(fields=['building', 'floor'], name='access_acce_buildin_c1364e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['zone', 'person_type'], name='access_acce_zone_id_2a9103_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['specific_person'], name='access_acce_specifi_9fca02_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['valid_from', 'valid_to'], name='access_acce_valid_f_e1b84e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['department', 'year_of_study'], name='access_acce_departm_bbf148_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_time'], name='access_acce_access__5ce7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['person', 'access_time'], name='access_acce_person__76fe39_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['zone', 'access_time'], name='access_acce_zone_id_33f19b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['result', 'access_time'], name='access_acce_result_799a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['session_id'], name='access_acce_session_91cc50_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['person', 'zone', 'access_time'], name='access_acce_person__1483bf_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['zone', 'result', 'access_time'], name='access_acce_zone_id_39aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='accessattempt',
            index=models.Index(fields=['attempt_time'], name='access_acce_attempt_276c84_idx'),
        ),
        migrations.AddIndex(
            model_name='accessattempt',
            index=models.Index(fields=['credential'], name='access_acce_credent_da253a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessattempt',
            index=models.Index(fields=['node', 'attempt_time'], name='access_acce_node_id_88d096_idx'),
        ),
        migrations.AddIndex(
            model_name='accessattempt',
            index=models.Index(fields=['person', 'attempt_time'], name='access_acce_person__4bf484_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceboundary',
            index=models.Index(fields=['zone'], name='access_geof_zone_id_f32bce_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceboundary',
            index=models.Index(fields=['boundary_type'], name='access_geof_boundar_fac4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['person', 'event_time'], name='access_geof_person__d938ec_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['zone', 'event_time'], name='access_geof_zone_id_ced505_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['event_type', 'event_time'], name='access_geof_event_t_c6be01_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorsession',
            index=models.Index(fields=['session_token'], name='access_twof_session_5acb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorsession',
            index=models.Index(fields=['person', 'created_at'], name='access_twof_person__e74217_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorsession',
            index=models.Index(fields=['status', 'expires_at'], name='access_twof_status_b59fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorsession',
            index=models.Index(fields=['otp_code'], name='access_twof_otp_cod_02fde3_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorlog',
            index=models.Index(fields=['session', 'event_time'], name='access_twof_session_17ba25_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorlog',
            index=models.Index(fields=['event_type', 'event_time'], name='access_twof_event_t_4c38f8_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneaccessrule',
            index=models.Index(fields=['zone', 'is_active'], name='access_zone_zone_id_327233_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneaccessrule',
            index=models.Index(fields=['rule_type'], name='access_zone_rule_ty_7fbda2_idx'),
        ),
        migrations.AddIndex(
            model_name='zonehierarchy',
            index=models.Index(fields=['ancestor', 'depth'], name='access_zone_ancesto_e40fef_idx'),
        ),
        migrations.AddIndex(
            model_name='zonehierarchy',
            index=models.Index(fields=['descendant'], name='access_zone_descend_7d33d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonehierarchy',
            unique_together={('ancestor', 'descendant')},
        ),
    ]
