# Generated by Django 5.2.13 on 2026-04-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofenceboundary',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='access.accesszone'),
        ),
    ]
