# Generated by Django 5.2.13 on 2026-04-11 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('attendance_daily', 'Daily Attendance'), ('attendance_weekly', 'Weekly Attendance'), ('attendance_monthly', 'Monthly Attendance'), ('visitor_daily', 'Daily Visitors'), ('visitor_weekly', 'Weekly Visitors'), ('access_summary', 'Access Summary'), ('security_audit', 'Security Audit'), ('device_health', 'Device Health Report'), ('occupancy', 'Occupancy Report')], max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField(default='08:00')),
                ('parameters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'next_run'], name='reports_rep_is_acti_75ce04_idx'), models.Index(fields=['report_type'], name='reports_rep_report__6fa768_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('export_type', models.CharField(choices=[('attendance', 'Attendance Data'), ('visitors', 'Visitor Data'), ('access_logs', 'Access Logs'), ('device_data', 'Device Data')], max_length=20)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied to export')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='core.staff')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['export_type', 'created_at'], name='reports_exp_export__7b231e_idx'), models.Index(fields=['exported_by', 'created_at'], name='reports_exp_exporte_9cdfdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means record is archived')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('attendance_daily', 'Daily Attendance'), ('attendance_weekly', 'Weekly Attendance'), ('attendance_monthly', 'Monthly Attendance'), ('visitor_daily', 'Daily Visitors'), ('visitor_weekly', 'Weekly Visitors'), ('access_summary', 'Access Summary'), ('security_audit', 'Security Audit'), ('device_health', 'Device Health Report'), ('occupancy', 'Occupancy Report')], db_index=True, max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters (date range, filters, etc.)')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_via', models.CharField(blank=True, max_length=50)),
                ('delivered_to', models.CharField(blank=True, max_length=200)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to='core.staff')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['requested_by', 'requested_at'], name='reports_rep_request_a52b21_idx'), models.Index(fields=['status', 'requested_at'], name='reports_rep_status_6c0213_idx')],
            },
        ),
    ]
